import { Task } from '../core/types';
import { GitDiff } from '../git/operations';

/**
 * Generate PR description from task artifacts
 */
export function generatePRDescription(task: Task, diff: GitDiff): string {
  const { requirements, implementationPlan, reviewReport } = task.artifacts;
  
  let description = `# ${task.title}\n\n`;
  
  // Overview
  if (requirements?.userStory) {
    description += `## Overview\n\n${requirements.userStory}\n\n`;
  }
  
  // Changes Made
  description += `## Changes Made\n\n`;
  description += `- **Files Changed**: ${diff.summary.filesChanged}\n`;
  description += `- **Lines Added**: ${diff.summary.insertions}\n`;
  description += `- **Lines Deleted**: ${diff.summary.deletions}\n\n`;
  
  // Files Modified
  if (diff.files.length > 0) {
    description += `### Modified Files\n\n`;
    diff.files.forEach(file => {
      description += `- \`${file.path}\` (${file.status})\n`;
    });
    description += `\n`;
  }
  
  // Acceptance Criteria
  if (requirements?.acceptanceCriteria && requirements.acceptanceCriteria.length > 0) {
    description += `## Acceptance Criteria Met\n\n`;
    requirements.acceptanceCriteria.forEach((criterion, i) => {
      description += `- [x] ${criterion}\n`;
    });
    description += `\n`;
  }
  
  // Implementation Details
  if (implementationPlan?.approach) {
    description += `## Implementation Details\n\n${implementationPlan.approach}\n\n`;
  }
  
  // Testing
  if (implementationPlan?.testStrategy) {
    description += `## Testing\n\n${implementationPlan.testStrategy}\n\n`;
  }
  
  // Review Notes
  if (reviewReport) {
    description += `## Code Review\n\n`;
    description += `**Status**: ${reviewReport.approved ? '✅ Approved' : '⚠️ Needs Changes'}\n\n`;
    
    if (reviewReport.summary) {
      description += `${reviewReport.summary}\n\n`;
    }
    
    if (reviewReport.issues.length > 0) {
      const criticalIssues = reviewReport.issues.filter(i => i.severity === 'critical');
      const majorIssues = reviewReport.issues.filter(i => i.severity === 'major');
      const minorIssues = reviewReport.issues.filter(i => i.severity === 'minor');
      
      if (criticalIssues.length > 0) {
        description += `### Critical Issues (${criticalIssues.length})\n\n`;
        criticalIssues.forEach(issue => {
          description += `- **${issue.category}**: ${issue.description}\n`;
        });
        description += `\n`;
      }
      
      if (majorIssues.length > 0) {
        description += `### Major Issues (${majorIssues.length})\n\n`;
        majorIssues.forEach(issue => {
          description += `- **${issue.category}**: ${issue.description}\n`;
        });
        description += `\n`;
      }
      
      if (minorIssues.length > 0) {
        description += `### Minor Issues (${minorIssues.length})\n\n`;
        minorIssues.forEach(issue => {
          description += `- **${issue.category}**: ${issue.description}\n`;
        });
        description += `\n`;
      }
    }
  }
  
  // Related Task
  description += `## Related Task\n\n`;
  description += `Task ID: ${task.id}\n\n`;
  
  // Footer
  description += `---\n`;
  description += `*Generated by AI SDLC Wrapper with IBM Bob*\n`;
  
  return description;
}

/**
 * Generate a simple PR title from task
 */
export function generatePRTitle(task: Task): string {
  return task.title;
}

// Made with Bob
